version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest

conda:
  environment: environment.yaml

python:
  install:
  - method: pip
    path: .
