
# ==================================================================================================

def cmake():
  r'''
Return typical build files/folders generated by CMake.
  '''

  return ['CMakeFiles', 'CMakeCache.txt', 'cmake_install.cmake', 'Makefile']

# ==================================================================================================


