name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  pypi-publish:

    name: Upload release to PyPI

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/GooseSLURM

    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set latest release tag
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $LATEST_TAG
        echo "SETUPTOOLS_SCM_PRETEND_VERSION=$LATEST_TAG" >> $GITHUB_ENV

    - name: Install deps
      run: python -m pip install -U setuptools build wheel

    - name: Build
      run: python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
